services:
  backend-for-frontend:
    build:
      context: ${SERVICE_PATH:-services}/backend-for-frontend-python
      dockerfile: Dockerfile
    image: backend-for-frontend-python:latest
    ports:
      - "10115"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_SERVICE_NAME=backend-for-frontend

  image-picker:
    build:
      context: ${SERVICE_PATH:-services}/image-picker-python
      dockerfile: Dockerfile
    image: image-picker-python:latest
    ports:
      - "10116"
    environment:
      - BUCKET_NAME
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_SERVICE_NAME=image-picker-python

  meminator:
    build:
      context: ${SERVICE_PATH:-services}/meminator-python
      dockerfile: Dockerfile
    image: meminator-python:latest
    ports:
      - "10117"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_SERVICE_NAME=meminator-python

  phrase-picker:
    build:
      context: ${SERVICE_PATH:-services}/phrase-picker-python
      dockerfile: Dockerfile
    image: phrase-picker-python:latest
    ports:
      - "10118"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_SERVICE_NAME=phrase-picker-python

  web:
    build:
      context: ${SERVICE_PATH:-services}/web
      dockerfile: Dockerfile
      args:
        HONEYCOMB_API_KEY: ${HONEYCOMB_API_KEY}
    image: web:latest
    # volumes: # uncomment this for faster development on the frontend
    #   - ./services/web/dist:/usr/share/nginx/html # Mount directory containing static files -- only do this for development
    ports:
      - "10114:10114"
    depends_on:
      backend-for-frontend:
        condition: service_started
      image-picker:
        condition: service_started
      meminator:
        condition: service_started
      phrase-picker:
        condition: service_started
