apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service.name: backend-for-frontend
  name: backend-for-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      service.name: backend-for-frontend
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-python: "honeycomb/otel-autoinstrumentation"
      labels:
        academy-instrumentation-python-default: "true"
        service.name: backend-for-frontend
    spec:
      containers:
        - env:
            - name: OTEL_SERVICE_NAME
              value: backend-for-frontend
            - name: OTEL_PYTHON_DISABLED_INSTRUMENTATIONS
              value: aws-lambda
          image: services/backend-for-frontend-python:latest
          name: backend-for-frontend
          ports:
            - containerPort: 10115
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
