apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service.name: meminator
  name: meminator
  annotations:
    instrumentation.opentelemetry.io/inject-python: "honeycomb/otel-autoinstrumentation"
spec:
  replicas: 1
  selector:
    matchLabels:
      service.name: meminator

  template:
    metadata:
      labels:
        academy-instrumentation-python-default: "true"
        service.name: meminator
    spec:
      containers:
        - env:
            - name: OTEL_SERVICE_NAME
              value: meminator-python
          image: services/meminator-python:latest
          name: meminator
          ports:
            - containerPort: 10117
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
