apiVersion: v1
kind: Service
metadata:
  labels:
    service.name: web
  name: web
spec:
  ports:
    - name: "http"
      port: 10114
      targetPort: 10114
  selector:
    service.name: web
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: web-external
spec:
  type: LoadBalancer
  selector:
    service.name: web
  ports:
  - name: http
    port: 10114
    targetPort: 10114