apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service.name: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      service.name: web
  template:
    metadata:
      labels:
        academy-instrumentation-python-default: "true"
        service.name: web
    spec:
      containers:
        - image: services/web:latest
          name: web
          ports:
            - containerPort: 10114
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
